sonar.projectKey=belencost_contador_clics
sonar.organization=belencost
sonar.python.version=3.10
sonar.sources=src
sonar.tests=tests
sonar.inclusions=**/*.py
sonar.language=py

# Direccion del reporte de cobertura de tus pruebas
sonar.python.coverage.reportPaths=coverage.xml