name: Integracion Continua (CI)

on:
  push:
    branches: [ main ]

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Sonar necesita todo el historial para analizar

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Generar el reporte de cobertura y correr tests
    - name: Ejecutar pruebas y reporte de cobertura
      run: |
        python -m pytest --cov=src --cov-report=xml

    # Métricas
    - name: Análisis de Código con SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # Notificación final a Discord
    - name: Notificar a Discord
      if: always()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        export TZ="America/Argentina/Buenos_Aires"
        FECHA=$(date +"%d/%m/%Y a las %H:%M:%S")
        LINK="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        
        if [ "${{ job.status }}" == "success" ]; then
          curl -H "Content-Type: application/json" -d "{\"content\": \"✅ **¡Éxito!** Las pruebas y el análisis de SonarCloud pasaron correctamente. Código desplegandose en producción.\n📅 **Hora del reporte:** $FECHA\n🔗 [Hacé clic acá para ver los detalles]($LINK)\"}" $DISCORD_WEBHOOK
        else
          curl -H "Content-Type: application/json" -d "{\"content\": \"❌ **¡Alerta!** El pipeline falló. Revisar pruebas o métricas de calidad.\n📅 **Hora del reporte:** $FECHA\n🔗 [Hacé clic acá para ver el error]($LINK)\"}" $DISCORD_WEBHOOK
        fi